import { useEffect, useMemo, useState } from 'react'
import { useAuth } from '../../context/useAuth'

const tabs = { parents: ['parent'], students: ['student'], staff: ['admin', 'principal', 'teacher', 'accountant'] }
const relativeTime = date => {
  const seconds = Math.max(0, Math.floor((Date.now() - new Date(date).getTime()) / 1000))
  if (seconds < 60) return 'just now'; if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`; if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`; return `${Math.floor(seconds / 86400)}d ago`
}
export default function ActivityLog() {
  const { supabase } = useAuth(); const [tab, setTab] = useState('staff'); const [rows, setRows] = useState([]); const [query, setQuery] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { let active = true; (async () => { setLoading(true); let request = supabase.from('audit_logs').select('*').order('created_at', { ascending: false }).limit(500); if (from) request = request.gte('created_at', `${from}T00:00:00`); if (to) request = request.lte('created_at', `${to}T23:59:59.999`); const { data, error: loadError } = await request; if (!active) return; setRows(data ?? []); setError(loadError?.message ?? ''); setLoading(false) })(); return () => { active = false } }, [supabase, from, to])
  const shown = useMemo(() => rows.filter(row => tabs[tab].includes(row.actor_role) && `${row.metadata?.actor_name ?? ''} ${row.description ?? ''}`.toLowerCase().includes(query.toLowerCase())), [rows, tab, query])
  return <section className="dash-section"><div className="dash-page-header"><div><h1 className="dash-page-title">Activity Log</h1><p className="dash-page-sub">Recent portal activity. Staff entries show the user role.</p></div></div><div className="portal-workspace"><div className="card"><div className="portal-card-title"><div role="tablist" className="portal-tabs">{Object.keys(tabs).map(key => <button key={key} role="tab" className={`btn ${tab === key ? 'primary' : 'secondary'}`} onClick={() => setTab(key)}>{key[0].toUpperCase() + key.slice(1)}</button>)}</div><label className="portal-inline-search">Search<input value={query} onChange={e => setQuery(e.target.value)} placeholder="Name or activity" /></label></div><div className="portal-action-row"><label>From<input type="date" value={from} onChange={e => setFrom(e.target.value)} /></label><label>To<input type="date" value={to} onChange={e => setTo(e.target.value)} /></label></div>{error && <p className="portal-notice error">{error}</p>}{loading ? <p className="muted">Loading activity…</p> : !shown.length ? <p className="muted">No {tab} activity matches the current filters.</p> : <div className="portal-table-wrap"><table className="portal-table"><thead><tr><th>Actor</th><th>Activity</th><th>When</th></tr></thead><tbody>{shown.map(row => <tr key={row.id}><td><strong>{row.metadata?.actor_name || 'Portal user'}</strong><small>{row.actor_role || 'unknown'}</small></td><td>{row.description || row.action_type}</td><td title={new Date(row.created_at).toLocaleString('en-ZW')}><strong>{relativeTime(row.created_at)}</strong><small>{new Date(row.created_at).toLocaleString('en-ZW')}</small></td></tr>)}</tbody></table></div>}</div></div></section>
}
