import { useEffect, useMemo, useRef, useState } from 'react'
import { getFeeAmount } from '../../lib/FeeStructure'
import { supabase as fallback } from '../../lib/supabaseClient'
import { getCampusForLevel } from '../../data/classOptions'
import { useSchoolClasses } from '../../hooks/useSchoolClasses'

const headers=['admission_no','first_name','last_name','dob','sex','parent_mobile','class_level','class_stream','address']
const template=`${headers.join(',')}\n0012026,NAME,SURNAME,14/04/11,F,+263712345678,Form 1,White,ADDRESS\n`
const cells=line=>{let v=[],c='',q=false;for(const x of line){if(x==='"')q=!q;else if(x===','&&!q){v.push(c.trim());c=''}else c+=x}v.push(c.trim());return v}
const date=v=>/^\d{2}\/\d{2}\/\d{2}$/.test(v)?`${Number(v.slice(6))>30?'19':'20'}${v.slice(6)}-${v.slice(3,5)}-${v.slice(0,2)}`:''
export default function BulkStudentImport({onSaved,onViewLearners,supabase:provided}){
 const db=provided??fallback,file=useRef(),[source,setSource]=useState(''),[name,setName]=useState(''),[existing,setExisting]=useState(new Set()),[drag,setDrag]=useState(false),[paste,setPaste]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState('')
 const { classes: schoolClasses, loading: classesLoading } = useSchoolClasses(db)
 const base=useMemo(()=>{const lines=source.trim().split(/\r?\n/).filter(Boolean);if(!lines.length)return[];if(cells(lines[0]).join(',')!==headers.join(','))return[{line:1,error:`Header must be: ${headers.join(', ')}`}];return lines.slice(1).map((line,i)=>{const x=cells(line),r=Object.fromEntries(headers.map((h,j)=>[h,x[j]||'']));r.line=i+2;r.dob=date(r.dob);let e=[];if(x.length!==headers.length)e.push('Wrong column count');if(!/^\d{7,}$/.test(r.admission_no))e.push('Invalid admission number (use 0012026)');if(!r.first_name||!r.last_name)e.push('Missing learner name');if(!r.dob)e.push('Missing date of birth');if(!['M','F'].includes(r.sex))e.push('Sex must be M or F');if(r.parent_mobile&&!/^\+263\d{9}$/.test(r.parent_mobile))e.push('Invalid parent phone');if(!classesLoading&&!schoolClasses.some(o=>o.class_level===r.class_level&&(o.class_stream||'')===r.class_stream))e.push('Invalid class or stream');r.error=e.join('; ');return r})},[source, schoolClasses, classesLoading])
 const nums=base.map(r=>r.admission_no).filter(Boolean)
 useEffect(()=>{let ok=true;if(!nums.length)return setExisting(new Set());db.from('students').select('admission_number').in('admission_number',nums).then(({data})=>ok&&setExisting(new Set((data||[]).map(r=>r.admission_number))));return()=>{ok=false}},[nums.join('|'),db])
 const rows=useMemo(()=>{const count=nums.reduce((a,n)=>({...a,[n]:(a[n]||0)+1}),{});return base.map(r=>({...r,error:[r.error,r.admission_no&&count[r.admission_no]>1?'Duplicate admission number in file':'',existing.has(r.admission_no)?'Admission number already exists':''].filter(Boolean).join('; ')}))},[base,nums,existing]);const valid=rows.filter(r=>!r.error),bad=rows.filter(r=>r.error)
 const load=async f=>{if(f){setName(f.name);setMessage('');setSource(await f.text())}};const dl=()=>{const u=URL.createObjectURL(new Blob([template]));Object.assign(document.createElement('a'),{href:u,download:'reliance-learner-import-template.csv'}).click();URL.revokeObjectURL(u)};const errors=()=>{const u=URL.createObjectURL(new Blob([['line,admission_no,reason',...bad.map(r=>`${r.line},${r.admission_no},"${r.error}"`)].join('\n')]));Object.assign(document.createElement('a'),{href:u,download:'reliance-import-errors.csv'}).click();URL.revokeObjectURL(u)}
 const submit=async()=>{setSaving(true);setMessage('');const year=new Date().getFullYear(),term=`Term ${Math.min(3,Math.floor(new Date().getMonth()/4)+1)}`;const {data,error}=await db.from('students').insert(valid.map(r=>({full_name:`${r.first_name} ${r.last_name}`,admission_number:r.admission_no,date_of_birth:r.dob,sex:r.sex,parent_phone:r.parent_mobile||null,address:r.address||null,class_level:r.class_level,class_stream:r.class_stream,campus:getCampusForLevel(r.class_level),enrolled_year:year,status:'active'}))).select('id,class_level');if(error){setSaving(false);return setMessage(error.message)}const fee=await db.from('fee_balances').insert(data.map(s=>({student_id:s.id,term,academic_year:year,total_fees:getFeeAmount(s.class_level),amount_paid:0})));if(fee.error){await db.from('students').delete().in('id',data.map(s=>s.id));setSaving(false);return setMessage(`Import rolled back: ${fee.error.message}`)}setSaving(false);setMessage(`${data.length} learners imported, ${bad.length} skipped.`);onSaved?.()}
 return <section className="bulk-import"><div className="bulk-import-steps">{['Download template','Upload or paste','Review','Import'].map((x,i)=><span key={x}><b>{i+1}</b>{x}</span>)}</div><div className="card"><h2>Step 1 · Download template</h2><button className="btn secondary" onClick={dl}>Download CSV template</button><h2>Step 2 · Upload or paste</h2><button className={`bulk-drop-zone${drag?' is-dragging':''}`} onClick={()=>file.current.click()} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);load(e.dataTransfer.files[0])}}><b>⇧ Drop your CSV here or click to browse</b><small>{name||'CSV files only'}</small></button><input hidden ref={file} type="file" accept=".csv" onChange={e=>load(e.target.files[0])}/><button className="bulk-paste-toggle" onClick={()=>setPaste(!paste)}>Or paste CSV text</button>{paste&&<label>Paste CSV text<textarea rows="8" value={source} onChange={e=>{setName('Pasted CSV');setSource(e.target.value)}}/></label>}{source&&<><h2>Step 3 · Review validation</h2><p><b>{valid.length} valid</b> · <b>{bad.length} with errors</b> {bad.length>0&&<button className="btn secondary" onClick={errors}>Download error report</button>}</p><div className="portal-table-wrap"><table className="portal-table"><thead><tr><th>Line</th><th>Admission</th><th>Learner</th><th>Class</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.line}><td>{r.line}</td><td>{r.admission_no}</td><td>{r.first_name} {r.last_name}</td><td>{r.class_level} {r.class_stream}</td><td>{r.error||'✓ Valid'}</td></tr>)}</tbody></table></div><h2>Step 4 · Import</h2>{saving&&<progress value="50" max="100"/>}<button className="btn primary" disabled={!valid.length||saving} onClick={submit}>{saving?'Importing…':`Import ${valid.length} valid learners`}</button>{message&&<p className="portal-notice">{message} {onViewLearners&&message.includes('imported')&&<button onClick={onViewLearners}>View learners →</button>}</p>}</>}</div></section>
}
