import { useMemo, useRef, useState } from 'react'
import { getFeeAmount } from '../../lib/FeeStructure'
import { supabase } from '../../lib/supabaseClient'
import Button from '../ui/Button'
import PortalNotice from './PortalNotice'

const headers = ['admission_no', 'first_name', 'last_name', 'dob', 'sex', 'parent_mobile', 'class_level', 'class_stream', 'address']
const template = `${headers.join(',')}\nF1-2026-048,NAME,SURNAME,14/04/11,F,+263712345678,Form 1,White,ADDRESS\n`
const parseLine = line => { const values = []; let current = '', quoted = false; for (let index = 0; index < line.length; index += 1) { if (line[index] === '"') quoted = !quoted; else if (line[index] === ',' && !quoted) { values.push(current.trim()); current = '' } else current += line[index] } values.push(current.trim()); return values }
const asDate = value => { const match = /^(\d{2})\/(\d{2})\/(\d{2})$/.exec(value); return match ? `${Number(match[3]) > 30 ? '19' : '20'}${match[3]}-${match[2]}-${match[1]}` : '' }

export default function BulkStudentImport({ onSaved }) {
  const file = useRef(null); const [source, setSource] = useState(''); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const rows = useMemo(() => { const lines = source.trim().split(/\r?\n/).filter(Boolean); if (!lines.length) return []; if (parseLine(lines[0]).join(',') !== headers.join(',')) return [{ error: `Header must be ${headers.join(',')}` }]; return lines.slice(1).map((line, index) => { const cells = parseLine(line); const row = Object.fromEntries(headers.map((header, i) => [header, cells[i] || ''])); row.dob = asDate(row.dob); row.line = index + 2; const issues = []; if (cells.length !== headers.length) issues.push('wrong column count'); if (!/^F1-\d{4}-\d{3}$/.test(row.admission_no)) issues.push('invalid admission'); if (!row.first_name || !row.last_name || !row.dob) issues.push('name and DOB required'); if (!['M', 'F'].includes(row.sex)) issues.push('sex M/F'); if (row.parent_mobile && !/^\+263\d{9}$/.test(row.parent_mobile)) issues.push('phone'); if (!row.class_level || !row.class_stream) issues.push('class'); row.error = issues.join(', '); return row }) }, [source])
  const ready = rows.filter(row => !row.error)
  const download = () => { const url = URL.createObjectURL(new Blob([template], { type: 'text/csv' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'reliance-student-import-template.csv'; anchor.click(); URL.revokeObjectURL(url) }
  const importRows = async () => { setError(''); setNotice(''); if (!ready.length || ready.length !== rows.length) return setError('Correct validation errors before importing.'); if (!supabase) return setError('Supabase is not configured.'); setSaving(true); const { data, error: studentError } = await supabase.from('students').insert(ready.map(row => ({ full_name: `${row.first_name} ${row.last_name}`, admission_number: row.admission_no, date_of_birth: row.dob, sex: row.sex, parent_phone: row.parent_mobile || null, address: row.address || null, class_level: row.class_level, class_stream: row.class_stream, campus: row.class_level.startsWith('Form') ? 'senior' : 'junior', enrolled_year: 2026, status: 'active' }))).select('id, class_level'); if (studentError) { setSaving(false); return setError(studentError.message) }; const { error: feeError } = await supabase.from('fee_balances').insert(data.map(student => ({ student_id: student.id, term: 'Term 3', academic_year: 2026, total_fees: getFeeAmount(student.class_level), amount_paid: 0 }))); if (feeError) { await supabase.from('students').delete().in('id', data.map(student => student.id)); setSaving(false); return setError(`Import rolled back: ${feeError.message}`) }; setNotice(`${data.length} learners imported with Term 3 fees.`); setSource(''); setSaving(false); onSaved?.() }
  return <section className="portal-workspace"><div className="portal-card"><h2>CSV learner import</h2><PortalNotice message={notice} error={error} /><div className="portal-action-row"><Button type="button" variant="secondary" onClick={download}>Download template</Button><Button type="button" variant="secondary" onClick={() => file.current?.click()}>Choose CSV</Button><input hidden ref={file} type="file" accept=".csv" onChange={async event => { const selected = event.target.files?.[0]; if (selected) setSource(await selected.text()) }} /></div><label>Paste CSV<textarea rows="8" value={source} onChange={event => setSource(event.target.value)} /></label>{!!rows.length && <div className="portal-table-wrap"><table className="portal-table"><thead><tr><th>Line</th><th>Admission</th><th>Name</th><th>Class</th><th>Status</th></tr></thead><tbody>{rows.map(row => <tr key={row.line || row.error}><td>{row.line || '—'}</td><td>{row.admission_no}</td><td>{row.first_name} {row.last_name}</td><td>{row.class_level} {row.class_stream}</td><td>{row.error || 'Ready'}</td></tr>)}</tbody></table></div>}<Button type="button" disabled={saving || !ready.length || ready.length !== rows.length} onClick={importRows}>{saving ? 'Importing…' : `Import ${ready.length} learners`}</Button></div></section>
}
