import { useEffect, useState } from 'react'
import Button from '../ui/Button'
import Card from '../ui/Card'
import PortalNotice from './PortalNotice'

export default function ClassManager({ supabase, onChanged }) {
  const [classes, setClasses] = useState([])
  const [form, setForm] = useState({ class_level: '', class_stream: '', campus: 'junior' })
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')
  const [setupRequired, setSetupRequired] = useState(false)
  const isMissingTable = value => ['PGRST205', '42P01'].includes(value?.code)
  const load = async () => { const { data, error: loadError } = await supabase.from('school_classes').select('*').order('campus').order('class_level'); if (loadError) { if (isMissingTable(loadError)) setSetupRequired(true); else setError(loadError.message) } else { setSetupRequired(false); setClasses(data ?? []) } }
  useEffect(() => { load() }, [supabase])
  const save = async event => { event.preventDefault(); setError(''); const { error: saveError } = await supabase.from('school_classes').insert({ ...form, class_level: form.class_level.trim(), class_stream: form.class_stream.trim() || null }); if (saveError) return isMissingTable(saveError) ? setSetupRequired(true) : setError(saveError.message); setForm({ class_level: '', class_stream: '', campus: 'junior' }); setNotice('Class saved. It is now available when adding learners.'); load(); onChanged?.() }
  const toggle = async row => { const { error: saveError } = await supabase.from('school_classes').update({ active: !row.active, updated_at: new Date().toISOString() }).eq('id', row.id); if (saveError) setError(saveError.message); else { load(); onChanged?.() } }
  return <div className="dash-section"><div className="dash-page-header"><div><h1 className="dash-page-title">Class management</h1><p className="dash-page-sub">Add the class levels and streams your school needs.</p></div></div>{error && <PortalNotice tone="error">{error}</PortalNotice>}{notice && <PortalNotice>{notice}</PortalNotice>}{setupRequired ? <Card><h2>Class management setup required</h2><p className="muted">The school classes database update has not been applied yet. Ask the system administrator to apply the latest Supabase migrations, then return here to add classes.</p></Card> : <div className="portal-workspace"><Card><h2>Add a class</h2><form className="form portal-form" onSubmit={save}><label>Class level<input required value={form.class_level} placeholder="e.g. Grade 8" onChange={e => setForm(value => ({ ...value, class_level: e.target.value }))} /></label><label>Stream (optional)<input value={form.class_stream} placeholder="e.g. Blue" onChange={e => setForm(value => ({ ...value, class_stream: e.target.value }))} /></label><label>Campus<select value={form.campus} onChange={e => setForm(value => ({ ...value, campus: e.target.value }))}><option value="junior">Junior</option><option value="senior">Senior</option></select></label><Button type="submit">Add class</Button></form></Card><Card><h2>Administrator-added classes</h2><div className="portal-table-wrap"><table className="portal-table"><thead><tr><th>Class level</th><th>Stream</th><th>Campus</th><th>Status</th><th /></tr></thead><tbody>{classes.length ? classes.map(row => <tr key={row.id}><td>{row.class_level}</td><td>{row.class_stream || '—'}</td><td>{row.campus}</td><td>{row.active ? 'Active' : 'Inactive'}</td><td><Button variant="secondary" type="button" onClick={() => toggle(row)}>{row.active ? 'Deactivate' : 'Activate'}</Button></td></tr>) : <tr><td colSpan="5" className="muted">No additional classes have been added.</td></tr>}</tbody></table></div></Card></div>}</div>
}
