import { useEffect, useMemo, useState } from 'react'
import Button from '../ui/Button'
import Card from '../ui/Card'
import PortalNotice from './PortalNotice'
import { useAuth } from '../../context/useAuth'

const term = () => String(Math.min(3, Math.floor(new Date().getMonth() / 4) + 1))
const blank = () => ({ classKey: '', subject: '', title: '', assessment_type: 'weekly', total_marks: '100', assessment_date: new Date().toISOString().slice(0, 10), term: term(), academic_year: new Date().getFullYear() })
const key = row => `${row.class_level}::${row.class_stream || ''}`

export default function CourseWork() {
  const { supabase, user, profile } = useAuth()
  const [students, setStudents] = useState([]), [assessments, setAssessments] = useState([]), [form, setForm] = useState(blank), [reuseAssessment, setReuseAssessment] = useState(''), [reuseClassKey, setReuseClassKey] = useState(''), [marks, setMarks] = useState({}), [selected, setSelected] = useState(''), [error, setError] = useState(''), [notice, setNotice] = useState(''), [saving, setSaving] = useState(false)
  const classes = useMemo(() => [...new Map(students.map(row => [key(row), row])).entries()], [students])
  const selectedAssessment = assessments.find(row => row.id === selected)
  const selectedStudents = useMemo(() => selectedAssessment ? students.filter(row => row.class_level === selectedAssessment.class_level && (row.class_stream || '') === (selectedAssessment.class_stream || '')) : [], [students, selectedAssessment])
  const load = async () => {
    const [learners, work] = await Promise.all([
      supabase.from('students').select('id,full_name,admission_number,class_level,class_stream,campus').eq('status','active').order('full_name'),
      supabase.from('coursework_assessments').select('*').eq('teacher_id', user.id).order('assessment_date', { ascending: false }),
    ])
    if (learners.error || work.error) setError(learners.error?.message || work.error?.message)
    setStudents(learners.data || []); setAssessments(work.data || [])
  }
  useEffect(() => { load() }, [supabase, user.id])
  useEffect(() => { if (!selected) return; supabase.from('coursework_marks').select('student_id,score').eq('assessment_id', selected).then(({ data, error: requestError }) => { if (requestError) setError(requestError.message); else setMarks(Object.fromEntries((data || []).map(row => [row.student_id, String(row.score)]))) }) }, [selected, supabase])
  const create = async event => { event.preventDefault(); setError(''); setNotice(''); const source = classes.find(([value]) => value === form.classKey)?.[1]; if (!source) return setError('Choose a class.'); if (!form.subject.trim() || !form.title.trim()) return setError('Enter the subject and assessment title.'); setSaving(true)
    const { data, error: requestError } = await supabase.from('coursework_assessments').insert({ teacher_id: user.id, campus: source.campus || profile?.campus || 'senior', class_level: source.class_level, class_stream: source.class_stream || null, subject: form.subject.trim(), title: form.title.trim(), assessment_type: form.assessment_type, total_marks: Number(form.total_marks), assessment_date: form.assessment_date, term: form.term, academic_year: Number(form.academic_year) }).select().single(); setSaving(false)
    if (requestError) return setError(requestError.message); setAssessments(rows => [data, ...rows]); setSelected(data.id); setMarks({}); setForm(blank()); setNotice('Assessment created. Enter marks below, then save once.') }
  const reuse = async event => { event.preventDefault(); setError(''); setNotice(''); const source = assessments.find(row => row.id === reuseAssessment); const target = classes.find(([value]) => value === reuseClassKey)?.[1]; if (!source || !target) return setError('Choose an existing assessment and another class.'); if (source.class_level === target.class_level && (source.class_stream || '') === (target.class_stream || '')) return setError('Choose a different class for this assessment.'); setSaving(true)
    const { id, created_at, ...copy } = source; const { data, error: requestError } = await supabase.from('coursework_assessments').insert({ ...copy, teacher_id: user.id, campus: target.campus || profile?.campus || 'senior', class_level: target.class_level, class_stream: target.class_stream || null }).select().single(); setSaving(false)
    if (requestError) return setError(requestError.message); setAssessments(rows => [data, ...rows]); setSelected(data.id); setMarks({}); setReuseAssessment(''); setReuseClassKey(''); setNotice(`Assessment copied to ${target.class_level} ${target.class_stream || ''}. Enter marks for the new class below.`) }
  const saveMarks = async () => { if (!selectedAssessment) return; const invalid = Object.values(marks).some(value => value !== '' && (Number(value) < 0 || Number(value) > Number(selectedAssessment.total_marks))); if (invalid) return setError(`Marks must be between 0 and ${selectedAssessment.total_marks}.`); setSaving(true); setError('')
    const rows = selectedStudents.filter(student => marks[student.id] !== '' && marks[student.id] !== undefined).map(student => ({ assessment_id: selected, student_id: student.id, score: Number(marks[student.id]) })); const { error: requestError } = rows.length ? await supabase.from('coursework_marks').upsert(rows, { onConflict: 'assessment_id,student_id' }) : { error: null }; setSaving(false); if (requestError) return setError(requestError.message); setNotice(`${rows.length} coursework mark${rows.length === 1 ? '' : 's'} saved.`) }
  const completed = selectedStudents.filter(student => marks[student.id] !== '' && marks[student.id] !== undefined).length
  return <section className="coursework-page"><header className="grade-entry-heading"><p className="eyebrow">Teacher workspace</p><h1>Course Work</h1><p>Create weekly, monthly or exam assessments and enter the whole class at once.</p></header>{error && <PortalNotice tone="error">{error}</PortalNotice>}{notice && <PortalNotice>{notice}</PortalNotice>}
    <Card><form className="form portal-form" onSubmit={create}><h2>1. Create an assessment</h2><label>Class<select required value={form.classKey} onChange={e => setForm(value => ({ ...value, classKey: e.target.value }))}><option value="">Choose assigned class</option>{classes.map(([value,row]) => <option key={value} value={value}>{row.class_level} {row.class_stream || ''}</option>)}</select></label><label>Subject<input required value={form.subject} onChange={e => setForm(value => ({ ...value, subject: e.target.value }))} placeholder="e.g. Mathematics" /></label><label>Assessment title<input required value={form.title} onChange={e => setForm(value => ({ ...value, title: e.target.value }))} placeholder="e.g. Week 4 fractions test" /></label><label>Type<select value={form.assessment_type} onChange={e => setForm(value => ({ ...value, assessment_type: e.target.value }))}><option value="weekly">Weekly assessment</option><option value="monthly">Monthly assessment</option><option value="exam">Exam</option></select></label><label>Total marks<input required min="1" type="number" value={form.total_marks} onChange={e => setForm(value => ({ ...value, total_marks: e.target.value }))} /></label><label>Date<input required type="date" value={form.assessment_date} onChange={e => setForm(value => ({ ...value, assessment_date: e.target.value }))} /></label><Button type="submit" disabled={saving}>{saving ? 'Creating…' : 'Create assessment'}</Button></form></Card>
    <Card><form className="form portal-form" onSubmit={reuse}><h2>2. Reuse for another class</h2><p className="muted" style={{gridColumn:'1 / -1',margin:0}}>Copy an existing assessment to another one of your classes. The new class starts with blank marks.</p><label>Existing assessment<select value={reuseAssessment} onChange={e => setReuseAssessment(e.target.value)}><option value="">Choose assessment</option>{assessments.map(row => <option key={row.id} value={row.id}>{row.subject} · {row.title} ({row.class_level} {row.class_stream || ''})</option>)}</select></label><label>Other class<select value={reuseClassKey} onChange={e => setReuseClassKey(e.target.value)}><option value="">Choose another class</option>{classes.map(([value,row]) => <option key={value} value={value}>{row.class_level} {row.class_stream || ''}</option>)}</select></label><Button type="submit" disabled={saving}>{saving ? 'Copying…' : 'Copy assessment to class'}</Button></form></Card>
    <Card><div className="coursework-heading"><div><h2>3. Enter class marks</h2><p>Select an assessment to see who is marked and who is still missing.</p></div><label>Assessment<select value={selected} onChange={e => setSelected(e.target.value)}><option value="">Choose assessment</option>{assessments.map(row => <option key={row.id} value={row.id}>{row.subject} · {row.title} ({row.class_level} {row.class_stream || ''})</option>)}</select></label></div>{selectedAssessment && <><p className="muted">{completed}/{selectedStudents.length} marks entered · Missing marks remain blank until saved.</p><div className="portal-table-wrap"><table className="portal-table"><thead><tr><th>Learner</th><th>Admission no.</th><th>Mark / {selectedAssessment.total_marks}</th><th>Status</th></tr></thead><tbody>{selectedStudents.map(student => { const value = marks[student.id] ?? ''; return <tr key={student.id}><td><strong>{student.full_name}</strong></td><td>{student.admission_number}</td><td><input aria-label={`Mark for ${student.full_name}`} type="number" min="0" max={selectedAssessment.total_marks} value={value} onChange={e => setMarks(current => ({ ...current, [student.id]: e.target.value }))} /></td><td><span className={`class-status ${value === '' ? 'is-inactive' : 'is-active'}`}>{value === '' ? 'Missing' : 'Entered'}</span></td></tr>})}</tbody></table></div><Button type="button" onClick={saveMarks} disabled={saving}>{saving ? 'Saving…' : `Save ${completed} marks`}</Button></>}</Card></section>
}
