import { useEffect, useMemo, useState } from 'react'
import Button from '../ui/Button'
import Card from '../ui/Card'
import PortalNotice from './PortalNotice'
import StudentSelector from './StudentSelector'

const CURRENT_YEAR = 2026
const CURRENT_TERM = 'Term 3'
const TERMS = ['Term 1', 'Term 2', 'Term 3']
const money = (value) => `$${Number(value ?? 0).toFixed(2)}`
const balance = (row) => Number(row.total_fees) - Number(row.amount_paid)

export default function FeeManager({ students, loading, supabase, user, onBack }) {
  const [studentId, setStudentId] = useState(''); const [query, setQuery] = useState(''); const [year, setYear] = useState(CURRENT_YEAR); const [term, setTerm] = useState(CURRENT_TERM); const [form, setForm] = useState({ total_fees: '0', amount_paid: '0' }); const [history, setHistory] = useState([]); const [notice, setNotice] = useState(''); const [error, setError] = useState('')
  const student = students.find(row => row.id === studentId)
  const years = useMemo(() => student ? Array.from({ length: Math.max(1, CURRENT_YEAR - Number(student.enrolled_year) + 1) }, (_, index) => Number(student.enrolled_year) + index) : [], [student])
  const current = history.find(row => row.academic_year === Number(year) && row.term === term)
  const loadHistory = async () => { if (!studentId) return setHistory([]); const { data, error: requestError } = await supabase.from('fee_balances').select('*').eq('student_id', studentId).order('academic_year', { ascending: false }).order('term', { ascending: false }); if (requestError) setError(requestError.message); else setHistory(data ?? []) }
  useEffect(() => { setYear(CURRENT_YEAR); setTerm(CURRENT_TERM); setForm({ total_fees: '0', amount_paid: '0' }); setNotice(''); setError(''); loadHistory() }, [studentId])
  useEffect(() => { setForm(current ? { total_fees: String(current.total_fees), amount_paid: String(current.amount_paid) } : { total_fees: '0', amount_paid: '0' }) }, [studentId, year, term, current?.id])
  const save = async (event) => { event.preventDefault(); setError(''); setNotice(''); if (!student) return setError('Select a learner first.'); const before = current ? { paid: Number(current.amount_paid), balance: balance(current) } : { paid: 0, balance: 0 }; const next = { student_id: student.id, term, academic_year: Number(year), total_fees: Number(form.total_fees), amount_paid: Number(form.amount_paid), updated_by: user.id, updated_at: new Date().toISOString() }; const { error: requestError } = await supabase.from('fee_balances').upsert(next, { onConflict: 'student_id,term,academic_year' }); if (requestError) return setError(requestError.message); const nextBalance = next.total_fees - next.amount_paid; setNotice(`Updated ${term} ${year}: Paid ${money(before.paid)} → ${money(next.amount_paid)}. Balance: ${money(before.balance)} → ${money(nextBalance)}.`); loadHistory() }
  return <section className="section white"><div className="container portal-content"><p className="eyebrow">Internal tool</p><h1>Fees</h1>{onBack && <Button variant="secondary" onClick={onBack}>Back to staff dashboard</Button>}{notice && <PortalNotice>{notice}</PortalNotice>}{error && <PortalNotice tone="error">{error}</PortalNotice>}<div className="portal-workspace"><Card><h2>Fee record</h2><StudentSelector students={students} value={studentId} onChange={setStudentId} query={query} onQueryChange={setQuery} loading={loading} />{student && <form className="form portal-form" onSubmit={save}><label>Academic year<select value={year} onChange={e => setYear(Number(e.target.value))}>{years.map(value => <option key={value} value={value}>{value}</option>)}</select></label><label>Term<select value={term} onChange={e => setTerm(e.target.value)}>{TERMS.map(value => <option key={value}>{value}</option>)}</select></label>{current ? <p className="portal-notice">Current record — {term} {year}: Total {money(current.total_fees)} · Paid {money(current.amount_paid)} · Balance owing {money(balance(current))} (last updated {new Date(current.updated_at).toLocaleDateString('en-ZW')})</p> : <p className="muted">No fee record yet for this term.</p>}<label>Total fees<input type="number" min="0" step="0.01" value={form.total_fees} onChange={e => setForm(value => ({ ...value, total_fees: e.target.value }))} required /></label><label>Amount paid<input type="number" min="0" step="0.01" value={form.amount_paid} onChange={e => setForm(value => ({ ...value, amount_paid: e.target.value }))} required /></label><Button type="submit">Save fee record</Button></form>}</Card><Card><h2>Fee history</h2>{history.length ? <div className="portal-table-wrap"><table className="portal-table"><thead><tr><th>Year</th><th>Term</th><th>Total</th><th>Paid</th><th>Balance</th></tr></thead><tbody>{history.map(row => <tr key={row.id}><td>{row.academic_year}</td><td>{row.term}</td><td>{money(row.total_fees)}</td><td>{money(row.amount_paid)}</td><td><strong className={balance(row) > 0 ? 'portal-balance-owing' : 'portal-balance-clear'}>{money(balance(row))}</strong></td></tr>)}</tbody></table></div> : <p className="muted">Select a learner to view fee history.</p>}</Card></div></div></section>
}
