import { useEffect, useMemo, useState } from 'react'
import Button from '../ui/Button'
import Card from '../ui/Card'
import PortalNotice from './PortalNotice'

const money = amount => `$${Number(amount || 0).toFixed(2)}`

export default function ParentUniformShop({ supabase, parentId, student }) {
  const [products, setProducts] = useState([]); const [cart, setCart] = useState([]); const [phone, setPhone] = useState(''); const [reference, setReference] = useState(''); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { supabase.from('inventory_products').select('id,name,sku,selling_price,stock_quantity,category').eq('category', 'Uniforms').gt('stock_quantity', 0).order('name').then(({ data, error }) => { setProducts(data ?? []); if (error) setError('Uniform shop is not available yet.') }) }, [supabase])
  const total = useMemo(() => cart.reduce((sum, item) => sum + Number(item.selling_price) * item.quantity, 0), [cart])
  const add = product => setCart(current => { const existing = current.find(item => item.id === product.id); return existing ? current.map(item => item.id === product.id ? { ...item, quantity: Math.min(item.quantity + 1, product.stock_quantity) } : item) : [...current, { ...product, quantity: 1 }] })
  const update = (id, quantity) => setCart(current => current.map(item => item.id === id ? { ...item, quantity: Math.max(1, Math.min(Number(quantity) || 1, item.stock_quantity)) } : item))
  const checkout = async event => { event.preventDefault(); setError(''); setNotice(''); if (!cart.length) return setError('Add at least one uniform item.')
    setSaving(true); const { error: orderError } = await supabase.from('parent_uniform_orders').insert({ parent_id: parentId, student_id: student.id, items: cart.map(({ id, name, quantity, selling_price }) => ({ product_id: id, name, quantity, unit_price: selling_price })), total, ecocash_phone: phone.replace(/\s/g, ''), ecocash_reference: reference.trim() || null, payment_status: 'pending' }); setSaving(false)
    if (orderError) return setError(orderError.message)
    setCart([]); setPhone(''); setReference(''); setNotice('Uniform order received. The school will verify the EcoCash payment and confirm collection.')
  }
  return <section className="parent-uniform-shop"><div className="parent-shop-heading"><div><p className="eyebrow">School shop</p><h2>Uniform purchase</h2><p>Order uniforms for {student.full_name} and pay using EcoCash.</p></div><span>{cart.reduce((sum, item) => sum + item.quantity, 0)} item{cart.reduce((sum, item) => sum + item.quantity, 0) === 1 ? '' : 's'} in cart</span></div>{error && <PortalNotice tone="error">{error}</PortalNotice>}{notice && <PortalNotice>{notice}</PortalNotice>}<div className="parent-shop-grid"><div className="parent-product-grid">{products.map(product => <Card key={product.id} className="parent-product-card"><span className="parent-product-category">Uniform</span><h3>{product.name}</h3><p>{product.stock_quantity} available</p><strong>{money(product.selling_price)}</strong><Button type="button" variant="secondary" onClick={() => add(product)}>Add to order</Button></Card>)}{!products.length && !error && <p className="muted">No uniform items are currently available.</p>}</div><Card className="parent-cart"><h3>Your order</h3>{cart.length ? <form onSubmit={checkout}><div className="parent-cart-lines">{cart.map(item => <div key={item.id}><div><strong>{item.name}</strong><span>{money(item.selling_price)} each</span></div><input aria-label={`Quantity for ${item.name}`} type="number" min="1" max={item.stock_quantity} value={item.quantity} onChange={event => update(item.id, event.target.value)} /><button type="button" onClick={() => setCart(current => current.filter(product => product.id !== item.id))}>Remove</button></div>)}</div><p className="parent-cart-total"><span>Total</span><strong>{money(total)}</strong></p><label>EcoCash number<input required inputMode="tel" placeholder="077 000 0000" value={phone} onChange={event => setPhone(event.target.value)} /></label><label>EcoCash reference <span className="field-optional">Optional</span><input placeholder="After payment" value={reference} onChange={event => setReference(event.target.value)} /></label><p className="parent-ecocash-note">Pay the school EcoCash number provided by the office, then add the payment reference. Orders are confirmed after verification.</p><Button type="submit" disabled={saving}>{saving ? 'Submitting order…' : `Place EcoCash order · ${money(total)}`}</Button></form> : <p className="muted">Choose uniform items to begin your order.</p>}</Card></div></section>
}
