import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useAuth } from '../../context/useAuth'
import DashboardLayout from '../../components/dashboard/DashboardLayout'
import DashboardHero from '../../components/dashboard/DashboardHero'
import DashboardCharts from '../../components/dashboard/DashboardCharts'
import ActivityFeed from '../../components/dashboard/ActivityFeed'
import GradeCard from '../../components/dashboard/GradeCard'
import FeeCard from '../../components/dashboard/FeeCard'
import '../../components/dashboard/dashboard.css';
import { invokeEdgeFunction } from '../../lib/edgeFunction';


const money = n => `$${Number(n || 0).toLocaleString(undefined,{maximumFractionDigits:0})}`
const gradeStatus = p => p >= 75 ? 'excellent' : p >= 50 ? 'good' : p >= 40 ? 'pass' : 'fail'
const summarizeAttendance = rows => { const counts = rows.reduce((a,r) => ({...a,[r.status]:(a[r.status]||0)+1}),{}); const total = rows.length || 1; return {...counts, percentage: Math.round(((counts.present||0)+(counts.late||0)*.5)/total*100)} }
export default function RoleDashboard({ role, selectedStudent, students = [], onStudentChange }) {
 const { supabase, user, profile } = useAuth(); const nav = useNavigate(); const [data,setData]=useState({loading:true,error:'',grades:[],fees:[],attendance:[],allStudents:[],profiles:[],announcements:[],sports:[]})
 const [seeding, setSeeding] = useState(false)
 const seedStaff = async () => {
   if (seeding) return
   setSeeding(true)
   const { data: result, error } = await invokeEdgeFunction(supabase, 'seed_reliance_staffing', {})
   setSeeding(false)
   if (error || result?.success === false) return alert(`Seeding failed: ${result?.error || error?.message || 'Please try again.'}`)
   alert('Staffing data seeded successfully.')
 }
 const load=useCallback(async()=>{ if(!user) return; setData(d=>({...d,loading:true,error:''}));
   const studentId=selectedStudent?.id; const studentRole=role==='student'||role==='parent'
   const gradeQuery=supabase.from('academic_records').select('*').order('created_at',{ascending:false}); const feeQuery=supabase.from('fee_balances').select('*').order('updated_at',{ascending:false}); const attendanceQuery=supabase.from('attendance').select('*').order('date',{ascending:false})
   if(studentRole && studentId){ gradeQuery.eq('student_id',studentId); feeQuery.eq('student_id',studentId); attendanceQuery.eq('student_id',studentId) }
   const requests=[gradeQuery,feeQuery,attendanceQuery,supabase.from('announcements').select('*').order('created_at',{ascending:false}).limit(5)]
   if(!studentRole) requests.push(supabase.from('students').select('id,full_name,class_level,class_stream').order('full_name'),supabase.from('profiles').select('id,role,full_name'),supabase.from('sports_records').select('*'))
   const res=await Promise.all(requests); const bad=res.find(r=>r.error); setData({loading:false,error:bad?.error?.message||'',grades:res[0].data||[],fees:res[1].data||[],attendance:res[2].data||[],announcements:res[3].data||[],allStudents:res[4]?.data||[],profiles:res[5]?.data||[],sports:res[6]?.data||[]})
 },[supabase,user,role,selectedStudent?.id]); useEffect(()=>{load()},[load])
 const gradeAverage=useMemo(()=>data.grades.length?Math.round(data.grades.reduce((s,g)=>s+Number(g.percentage??g.score??0),0)/data.grades.length):0,[data.grades]); const attendance=useMemo(()=>summarizeAttendance(data.attendance),[data.attendance]); const fee=data.fees[0]; const total=fee?.total_fees||0, paid=fee?.amount_paid||0, pending=Math.max(0,total-paid)
 const activities=[...data.grades.slice(0,3).map(g=>({title:'Grade updated',description:`${g.subject}: ${g.grade||g.percentage}%`,timestamp:new Date(g.created_at).toLocaleDateString(),color:'green'})),...data.announcements.slice(0,2).map(a=>({title:a.title,description:a.body,timestamp:new Date(a.created_at).toLocaleDateString()}))]
 if(data.loading) return <DashboardLayout role={role}><div className="dashboard-hero"><div className="dashboard-empty">Loading dashboard…</div></div></DashboardLayout>
 if(data.error) return <DashboardLayout role={role}><div className="dashboard-card"><h2>We could not load this dashboard</h2><p>{data.error}</p><button className="dashboard-button" onClick={load}>Try again</button></div></DashboardLayout>
 const name=profile?.full_name?.split(' ')[0]||selectedStudent?.full_name||'there'; const isLearner=['student','parent'].includes(role)
 if(isLearner) return <DashboardLayout role={role}><DashboardHero title={role==='parent'?`Welcome, ${name}! ${selectedStudent?.full_name || 'Your child'}’s dashboard`:`Welcome back, ${name}!`} subtitle={selectedStudent?.class_level && `${selectedStudent.class_level} ${selectedStudent.class_stream||''}`} stats={[{icon:'◆',label:'Current average',value:`${gradeAverage}%`,color:gradeAverage>=50?'green':'amber'},{icon:'$',label:'Fees status',value:pending?money(pending):'Paid',color:pending?'amber':'green'},{icon:'✓',label:'Attendance',value:`${attendance.percentage}%`,color:attendance.percentage>=80?'green':'amber'}]} actions={[{label:'View all grades',color:'secondary',onClick:()=>document.getElementById('grades')?.scrollIntoView()},{label:'Pay fees',onClick:()=>document.getElementById('fees')?.scrollIntoView()}]}/>{role==='parent'&&students.length>1&&<label className="dashboard-child-select">Viewing child<select value={selectedStudent?.id||''} onChange={e=>onStudentChange(e.target.value)}>{students.map(s=><option key={s.id} value={s.id}>{s.full_name} — {s.class_level}</option>)}</select></label>}<div className="dashboard-grid"><article id="grades" className="dashboard-card"><h2>Current term grades</h2><div className="grade-list">{data.grades.slice(0,6).map(g=><GradeCard key={g.id} subject={g.subject} grade={g.grade} percentage={g.percentage??g.score} status={gradeStatus(g.percentage??g.score)} comment={g.teachers_comment||g.comment}/>)}</div>{!data.grades.length&&<div className="dashboard-empty">No grades yet. They will appear once teachers enter them.</div>}</article><FeeCard paid={paid} pending={pending} total={total} dueDate={fee?.payment_date} onPay={()=>nav('/portal/student-dashboard#fees')}/><article className="dashboard-card"><h2>Attendance</h2><strong className="attendance-number">{attendance.percentage}%</strong><p>Present: {attendance.present||0} · Absent: {attendance.absent||0} · Late: {attendance.late||0}</p></article><DashboardCharts type="line" title="Performance trend" data={data.grades.slice().reverse().map((g,i)=>({label:g.term?`T${g.term}`:`#${i+1}`,value:Number(g.percentage??g.score??0)}))}/></div><ActivityFeed activities={activities}/></DashboardLayout>
 const isTeacher=role==='teacher'; const studentCount=data.allStudents.length; const teacherCount=data.profiles.filter(p=>p.role==='teacher').length; const gradesEntered=data.grades.length; const classData=Object.values(data.allStudents.reduce((a,s)=>{const k=`${s.class_level} ${s.class_stream||''}`;a[k]=(a[k]||0)+1;return a},{})).length
 const stats=isTeacher?[{icon:'▣',label:'Classes assigned',value:classData},{icon:'♟',label:'Students',value:studentCount},{icon:'✓',label:'Grades entered',value:gradesEntered,color:'green'}]:role==='principal'?[{icon:'♟',label:'Total students',value:studentCount},{icon:'▣',label:'Teachers',value:teacherCount},{icon:'$',label:'Fees collected',value:money(data.fees.reduce((s,f)=>s+Number(f.amount_paid||0),0)),color:'green'},{icon:'↗',label:'Enrollment',value:`${studentCount}`,color:'navy'}]:[{icon:'◉',label:'Total users',value:data.profiles.length},{icon:'♟',label:'Students',value:studentCount},{icon:'$',label:'Fees collected',value:money(data.fees.reduce((s,f)=>s+Number(f.amount_paid||0),0))},{icon:'!',label:'Outstanding',value:money(data.fees.reduce((s,f)=>s+Math.max(0,Number(f.total_fees||0)-Number(f.amount_paid||0)),0)),color:'red'},{icon:'●',label:'System health',value:'Healthy',color:'green'}]
 const enrollment=Object.entries(data.allStudents.reduce((a,s)=>{a[s.class_level]=(a[s.class_level]||0)+1;return a},{})).map(([label,value])=>({label,value})); const distribution=['A','B','C','D','E'].map(label=>({label,value:data.grades.filter(g=>(g.grade||'').startsWith(label)).length}))
 return <DashboardLayout role={role}><DashboardHero title={role==='principal'?`Good ${new Date().getHours()<12?'morning':'afternoon'}, Principal ${name}`:`Welcome, ${name}!`} subtitle={isTeacher?'Your classes, grading progress and learner insights.':'A complete school operations overview.'} stats={stats} actions={isTeacher?[{label:'Enter grades',onClick:()=>nav('/portal/teacher')}] : ['admin','principal'].includes(role)?[{label:'Manage users',onClick:()=>nav('/portal/staff')},{label:'Announcements',color:'secondary',onClick:()=>nav('/portal/announcements')},{label:'Seed Staffing Data',onClick:seedStaff}] :[{label:'Manage users',onClick:()=>nav('/portal/staff')},{label:'Announcements',color:'secondary',onClick:()=>nav('/portal/announcements')}]}/> <div className="dashboard-grid"><DashboardCharts title="Enrollment by grade" data={enrollment}/><DashboardCharts title="Academic performance" type="donut" data={distribution}/><article className="dashboard-card"><h2>{isTeacher?'My classes':'Fees status'}</h2>{isTeacher?data.allStudents.slice(0,8).map(s=><p key={s.id}><strong>{s.full_name}</strong> <small>{s.class_level} {s.class_stream}</small></p>):<FeeCard paid={data.fees.reduce((s,f)=>s+Number(f.amount_paid||0),0)} pending={data.fees.reduce((s,f)=>s+Math.max(0,Number(f.total_fees||0)-Number(f.amount_paid||0)),0)} total={data.fees.reduce((s,f)=>s+Number(f.total_fees||0),0)}/>}</article><article className="dashboard-card"><h2>{isTeacher?'Student trends':'Academic records'}</h2><p><strong>{gradesEntered}</strong> grades entered</p><p>School average: <strong>{gradeAverage}%</strong></p><Link to={isTeacher?'/portal/teacher':'/portal/staff'}>View details</Link></article>{!isTeacher&&<><article className="dashboard-card"><h2>Sports participation</h2><p>{data.sports.filter(s=>s.participated!==false).length} participation records</p></article><article className="dashboard-card"><h2>Alerts & issues</h2><p>{data.fees.filter(f=>Number(f.total_fees)>Number(f.amount_paid)).length} accounts with a balance.</p></article></>}</div><ActivityFeed activities={activities}/></DashboardLayout>
}
